//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fulbaso.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fulbaso.Common.Resources.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las credenciales ingresadas son invalidas..
        /// </summary>
        internal static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al identificarte con las credenciales solicitadas. Vuelve a intentar más tarde..
        /// </summary>
        internal static string AuthenticationFaulted {
            get {
                return ResourceManager.GetString("AuthenticationFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al parecer el servidor rechazó el pedido enviado! Vuelve a intentar más tarde..
        /// </summary>
        internal static string BadAjaxRequest {
            get {
                return ResourceManager.GetString("BadAjaxRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al parecer el servidor rechazó el pedido enviado..
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error accediendo a la base de datos..
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta dirección de email ya se encuentra registrada..
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validación de email.
        /// </summary>
        internal static string EmailRegistrationSubject {
            get {
                return ResourceManager.GetString("EmailRegistrationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en la aplicación.
        /// </summary>
        internal static string FatalException {
            get {
                return ResourceManager.GetString("FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Exceptions&quot;:[&quot;Ha ocurrido un error en la aplicación&quot;]}.
        /// </summary>
        internal static string FatalExceptionJson {
            get {
                return ResourceManager.GetString("FatalExceptionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd&apos; de &apos;MMMM, yyyy.
        /// </summary>
        internal static string LongDateFormat {
            get {
                return ResourceManager.GetString("LongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd&apos; de &apos;MMMM, yyyy hh:mm:ss tt.
        /// </summary>
        internal static string LongDateTimeFormat {
            get {
                return ResourceManager.GetString("LongDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrescar.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Algo salió mal! Volve a intentar más tarde..
        /// </summary>
        internal static string UnhandledAjaxException {
            get {
                return ResourceManager.GetString("UnhandledAjaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo salió mal durante la comunicación con el servidor..
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Exceptions&quot;:[&quot;¡Algo salió mal! Volve a intentar más tarde.&quot;]}.
        /// </summary>
        internal static string UnhandledExceptionJson {
            get {
                return ResourceManager.GetString("UnhandledExceptionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anónimo.
        /// </summary>
        internal static string UnregisteredUserDisplayName {
            get {
                return ResourceManager.GetString("UnregisteredUserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El recurso solicitado no existe en el servidor..
        /// </summary>
        internal static string WebResourceNotFound {
            get {
                return ResourceManager.GetString("WebResourceNotFound", resourceCulture);
            }
        }
    }
}
