/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Roles
	(
	Id int NOT NULL IDENTITY (1, 1),
	Description varchar(50) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Roles ADD CONSTRAINT
	PK_Roles PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Roles SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.UserPlaces ADD
	RoleId int NOT NULL
GO
ALTER TABLE dbo.UserPlaces
	DROP CONSTRAINT PK_UserPlaces
GO
ALTER TABLE dbo.UserPlaces ADD CONSTRAINT
	PK_UserPlaces PRIMARY KEY CLUSTERED 
	(
	UserId,
	PlaceId,
	RoleId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.UserPlaces ADD CONSTRAINT
	FK_UserPlaces_Roles FOREIGN KEY
	(
	RoleId
	) REFERENCES dbo.Roles
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.UserPlaces SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
